Examen2Progra4/Examen2Progra4/Models/Cliente.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Examen2Progra4.Models
{
    public class Cliente
    {
        public int cedula { get; set; }
        public string nombre { get; set; }
        public int telefono { get; set; }
        public string direccion { get; set; }
        public int medidor { get; set; }
        public Boolean tipoDomi { get; set; }

        public Cliente(int cedula, string nombre, int telefono, string direccion, int medidor, bool tipoDomi)
        {
            this.cedula = cedula;
            this.nombre = nombre;
            this.telefono = telefono;
            this.direccion = direccion;
            this.medidor = medidor;
            this.tipoDomi = tipoDomi;
        }

        public Cliente()
        {
        }
    }
}

Examen2Progra4/Examen2Progra4/Models/Consumo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Examen2Progra4.Models
{
    public class Consumo
    {
        public int mesU { get; set; }
        public int anoU { get; set; }
        public int consumoU { get; set; }
        public int cedulaU { get; set; }
        public int pagoU { get; set; } = 0;
        public Boolean pagadoU = false;
        public Boolean multaU = false;
        

        public Consumo(int mes, int ano, int consumo, int cedula)
        {
            this.mesU = mes;
            this.anoU = ano;
            this.consumoU = consumo;
            this.cedulaU = cedula;
        }

        public Consumo()
        {
        }
    }
}

Examen2Progra4/Examen2Progra4/Models/Empresa.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Examen2Progra4.Models
{
    public class Empresa
    {
        public string titulo { get; set; }
        public int costo { get; set; }
        public int baseDomiciliar { get; set; }
        public int baseEmpresarial { get; set; }
        public int fechaCobro { get; set; }
        public int fechaCorte { get; set; }
        public int multa { get; set; }

        public Empresa(string titulo, int costo, int baseDomiciliar, int baseEmpresarial, int fechaCobro, int fechaCorte, int multa)
        {
            this.titulo = titulo;
            this.costo = costo;
            this.baseDomiciliar = baseDomiciliar;
            this.baseEmpresarial = baseEmpresarial;
            this.fechaCobro = fechaCobro;
            this.fechaCorte = fechaCorte;
            this.multa = multa;
        }

        public Empresa()
        {
        }
    }
}

Examen2Progra4/Examen2Progra4/Models/ErrorViewModel.cs
using System;

namespace Examen2Progra4.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Examen2Progra4/Examen2Progra4/Controllers/AcueductoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Examen2Progra4.Collections;
using Examen2Progra4.Models;
using Microsoft.AspNetCore.Mvc;

namespace Examen2Progra4.Controllers
{
    public class AcueductoController : Controller
    {
        DataBase db;

        public AcueductoController()
        {
            db = new DataBase();
        }

        public IActionResult Index()
        {
            IEnumerable<Cliente> listaClientes = db.getClientes();
            return View(listaClientes);
        }

        public IActionResult agregarCLiente()
        {
            return View();
        }

        [HttpPost]
        public IActionResult agregarCliente(Cliente cliente)
        {
            int result=db.insertCliente(cliente);
            if (result == 1)
            {
                return View("Index");
            }
            else
            {
                return View();
            }
            
        }

        public IActionResult updateEmpresa()
        {
            return View();
        }

        [HttpPost]
        public IActionResult updateEmpresa(Empresa empresa)
        {
            int respuesta = db.updateEmpresa(empresa);
            if (respuesta == 1)
            {
                return View("verEmpresa");
            }
            else
            {
                return View();
            }
        }

        public IActionResult verEmpresa()
        {
            Empresa empresa = db.getEmpresa();

            return View(empresa);
        }

        public IActionResult agregarConsumo()
        {
               return View();
        }

        [HttpPost]
        public IActionResult agregarConsumo(Consumo consumo)
        {
            int respuesta=db.insertConsumo(consumo);
            if (respuesta == 1)
            {
                return View();
            }
            else
            {
                return View();
            }
        }

        public IActionResult pagarConsumo(string cedula)
        {
            IEnumerable<Consumo> listaConsumos=new List<Consumo>();
            if (!String.IsNullOrEmpty(cedula))
            {
                try
                {
                    listaConsumos = db.consumoPorPagar(int.Parse(cedula));
                }catch(Exception e)
                {

                }
            }
            
            return View(listaConsumos);
        }

        public IActionResult pagar(int mesU,int anoU,int cedula)
        {
            db.pagar(mesU, anoU, cedula);
            return View();
        }
    }
}

Examen2Progra4/Examen2Progra4/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Examen2Progra4.Models;

namespace Examen2Progra4.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Examen2Progra4/Examen2Progra4/Views/Acueducto/Index.cshtml
@model IEnumerable<Examen2Progra4.Models.Cliente>

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.cedula)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.telefono)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.direccion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.medidor)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.tipoDomi)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.cedula)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.telefono)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.direccion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.medidor)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.tipoDomi)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>

Examen2Progra4/Examen2Progra4/Views/Acueducto/agregarCLiente.cshtml
@model Examen2Progra4.Models.Cliente

@{
    ViewData["Title"] = "agregarCLiente";
}

<h2>agregarCLiente</h2>

<h4>Cliente</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="agregarCLiente">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="cedula" class="control-label"></label>
                <input asp-for="cedula" class="form-control" />
                <span asp-validation-for="cedula" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="nombre" class="control-label"></label>
                <input asp-for="nombre" class="form-control" />
                <span asp-validation-for="nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="telefono" class="control-label"></label>
                <input asp-for="telefono" class="form-control" />
                <span asp-validation-for="telefono" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="direccion" class="control-label"></label>
                <input asp-for="direccion" class="form-control" />
                <span asp-validation-for="direccion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="medidor" class="control-label"></label>
                <input asp-for="medidor" class="form-control" />
                <span asp-validation-for="medidor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <div class="checkbox">
                    <label>
                        <input asp-for="tipoDomi" /> @Html.DisplayNameFor(model => model.tipoDomi)
                    </label>
                </div>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Examen2Progra4/Examen2Progra4/Views/Acueducto/agregarConsumo.cshtml
@model Examen2Progra4.Models.Consumo

@{
    ViewData["Title"] = "agregarConsumo";
}

<h2>agregarConsumo</h2>

<h4>Consumo</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="agregarConsumo">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="mesU" class="control-label"></label>
                <input asp-for="mesU" class="form-control" />
                <span asp-validation-for="mesU" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="anoU" class="control-label"></label>
                <input asp-for="anoU" class="form-control" />
                <span asp-validation-for="anoU" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="consumoU" class="control-label"></label>
                <input asp-for="consumoU" class="form-control" />
                <span asp-validation-for="consumoU" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="cedulaU" class="control-label"></label>
                <input asp-for="cedulaU" class="form-control" />
                <span asp-validation-for="cedulaU" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Examen2Progra4/Examen2Progra4/Views/Acueducto/pagar.cshtml
@{
    ViewData["Title"] = "pagar";
}

<h2>pagar</h2>
<p>Su pago se a realizado con exito</p>

Examen2Progra4/Examen2Progra4/Views/Acueducto/pagarConsumo.cshtml
@model IEnumerable<Examen2Progra4.Models.Consumo>

@{
    ViewData["Title"] = "pagarConsumo";
}

<h2>pagarConsumo</h2>
@using (Html.BeginForm("pagarConsumo","Acueducto"))
{
    <p>
        Find by name: @Html.TextBox("cedula")
        <input type="submit" value="search" />
    </p>
}
<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.mesU)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.anoU)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.consumoU)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.cedulaU)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.pagoU)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.mesU)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.anoU)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.consumoU)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.cedulaU)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.pagoU)
    </td>
    <td>
        @Html.ActionLink("Pagar", "Pagar","Acueducto", new {mesU=item.mesU,anoU=item.anoU, cedula=item.cedulaU },null) |
        @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
        @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
    </td>
</tr>
}
    </tbody>
</table>

Examen2Progra4/Examen2Progra4/Views/Acueducto/updateEmpresa.cshtml
@model Examen2Progra4.Models.Empresa

@{
    ViewData["Title"] = "updateEmpresa";
}

<h2>updateEmpresa</h2>

<h4>Empresa</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="updateEmpresa">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="titulo" class="control-label"></label>
                <input asp-for="titulo" class="form-control" />
                <span asp-validation-for="titulo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="costo" class="control-label"></label>
                <input asp-for="costo" class="form-control" />
                <span asp-validation-for="costo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="baseDomiciliar" class="control-label"></label>
                <input asp-for="baseDomiciliar" class="form-control" />
                <span asp-validation-for="baseDomiciliar" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="baseEmpresarial" class="control-label"></label>
                <input asp-for="baseEmpresarial" class="form-control" />
                <span asp-validation-for="baseEmpresarial" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="fechaCobro" class="control-label"></label>
                <input asp-for="fechaCobro" class="form-control" />
                <span asp-validation-for="fechaCobro" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="fechaCorte" class="control-label"></label>
                <input asp-for="fechaCorte" class="form-control" />
                <span asp-validation-for="fechaCorte" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="multa" class="control-label"></label>
                <input asp-for="multa" class="form-control" />
                <span asp-validation-for="multa" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Examen2Progra4/Examen2Progra4/Views/Acueducto/verEmpresa.cshtml
@model Examen2Progra4.Models.Empresa

@{
    ViewData["Title"] = "verEmpresa";
}

<h2>verEmpresa</h2>

<div>
    <h4>Empresa</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.titulo)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.titulo)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.costo)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.costo)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.baseDomiciliar)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.baseDomiciliar)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.baseEmpresarial)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.baseEmpresarial)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.fechaCobro)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.fechaCobro)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.fechaCorte)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.fechaCorte)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.multa)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.multa)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

Examen2Progra4/Examen2Progra4/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

Examen2Progra4/Examen2Progra4/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Examen2Progra4/Examen2Progra4/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core MVC</li>
            <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398600">Add a Controller and View</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run &amp; Deploy</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure Web Apps</a></li>
        </ul>
    </div>
</div>

Examen2Progra4/Examen2Progra4/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Examen2Progra4</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Examen2Progra4</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Acueducto" asp-action="Index">Clientes</a></li>
                    <li><a asp-area="" asp-controller="Acueducto" asp-action="AgregarCliente">Agregar Clientes</a></li>
                    <li><a asp-area="" asp-controller="Acueducto" asp-action="verEmpresa">Empresa</a></li>
                    <li><a asp-area="" asp-controller="Acueducto" asp-action="updateEmpresa">Editar Empresa</a></li>
                    <li><a asp-area="" asp-controller="Acueducto" asp-action="agregarConsumo">Agregar Consumo</a></li>
                    <li><a asp-area="" asp-controller="Acueducto" asp-action="pagarConsumo">Pagar Consumo</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - Examen2Progra4</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>